### ISSUE TITLE
"/etc/motd.update.d/10-klipper-motd" not existing

### ISSUE THREAD

**Issue by EckigerLuca** [tomaski/klipper-motd#2]
Heya,
I can't edit the file because it doesn't exist. The only thing that has something to do with the motd is `motd.1`, but that has the default content inside.
I am running Debian 11 on a Pi 3b+.

**Comment by tomaski** [comment]
Hi @EckigerLuca ,

Couple of questions: 
1) Did you run the script as root?
2) What is the output of
```bash
ls -al /etc/motd.update.d/
```

**Comment by EckigerLuca** [comment]
Hey @tomaski,

I did run the script as root and the output of `ls -al /etc/motd.update.d/` is
```ls: cannot access '/etc/motd.update.d/': No such file or directory``` (same output when using sudo)

**Comment by tomaski** [comment]
try this:
```bash
sudo mkdir -p /etc/update-motd.d
```
and run install again

**Comment by EckigerLuca** [comment]
Okay, this is super weird:
The file now exists after running the command above and searching the file in WinSCP. I didn't even reinstall the script...
Well, thank you for your help!

**Comment by TexZeTech** [comment]
Well I just installed this on [mainsailOS](https://docs.mainsail.xyz/) as the base user with the only difference of running 

`cd ~ && git clone https://www.github.com/tomaski/klipper-motd.git` 

vs what is listed. 

~~The above issue is the exact same.~~

its not the same as this.
